/*
 * MIT License
 *
 * Copyright (c) 2025 shinhyo
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package io.github.shinhyo.signinwithapple.sample

import android.os.Bundle
import android.text.method.ScrollingMovementMethod
import androidx.appcompat.app.AppCompatActivity
import io.github.shinhyo.signinwithapple.SignInWithApple
import io.github.shinhyo.signinwithapple.model.AppleSignInResult
import io.github.shinhyo.signinwithapple.sample.databinding.ActivityViewBinding
import io.github.shinhyo.signinwithapple.sample.util.JsonUtil
import io.github.shinhyo.signinwithapple.sample.util.JwtUtil
import kotlinx.serialization.serializer
import timber.log.Timber
import java.util.UUID

class AndroidViewActivity : AppCompatActivity() {
    private lateinit var binding: ActivityViewBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityViewBinding.inflate(layoutInflater)
        setContentView(binding.root)

        binding.tvLog.movementMethod = ScrollingMovementMethod.getInstance()
        binding.btnStartLibrary.setOnClickListener {
            handleAppleSignIn()
        }
    }

    /**
     * Handles Apple Sign-In button click.
     * Generates a secure nonce, starts sign-in, and displays results.
     */
    private fun handleAppleSignIn() {
        // nonce is a cryptographically random value used to prevent replay attacks and to verify the integrity of the authentication response.
        // It must be generated by the client, sent to Apple, and then compared with the value in the id_token payload after authentication.
        // If the nonce in the JWT payload does not match the one you generated, the response should be considered invalid.
        val nonce = UUID.randomUUID().toString()

        SignInWithApple.signIn(this, nonce) { result ->
            result.onSuccess {
                showSuccessResult(it, nonce)
            }.onFailure {
                showFailureResult(it)
            }
        }
    }

    /**
     * Displays the result on success, including nonce check and JWT payload.
     */
    private fun showSuccessResult(credential: AppleSignInResult, nonce: String) {
        val json = JsonUtil.toPrettyJson(credential, serializer<AppleSignInResult>())
        val jwtPretty = JwtUtil.parseJwtPayload(credential.identityToken)
        val jwtPayload = try {
            org.json.JSONObject(jwtPretty)
        } catch (e: Exception) {
            val errorMsg = "onFailure\n\nJWT parse error: ${e.message}"
            Timber.e(errorMsg)
            binding.tvLog.text = errorMsg
            return
        }
        val jwtNonce = jwtPayload.optString("nonce")
        val nonceCheck = if (jwtNonce == nonce) "✅ nonce matches" else "❌ nonce mismatch"
        val message = buildString {
            appendLine("onSuccess")
            appendLine()
            appendLine(json)
            appendLine()
            appendLine("[JWT Payload]")
            appendLine(jwtPretty)
            appendLine()
            appendLine("[Nonce Check]")
            append(nonceCheck)
        }
        Timber.i(message)
        binding.tvLog.text = message
    }

    /**
     * Displays the result on failure.
     */
    private fun showFailureResult(error: Throwable) {
        val jsonMap = JsonUtil.toPrettyJsonMap(mapOf("error" to (error.message ?: "Unknown error")))
        val message = "onFailure\n\n$jsonMap"
        Timber.e(message)
        binding.tvLog.text = message
    }
}